export const CREATE_ZONE= 'CREATE_ZONE';
export const CREATE_ZONE_SUCCESS = 'CREATE_ZONE_SUCCESS';
export const CREATE_ZONE_FAILURE = 'CREATE_ZONE_FAILURE';
export const RESET_ZONE = 'RESET_ZONE';

export const DELETE_ZONE_SUCCESS = 'DELETE_ZONE_SUCCESS';
export const DELETE_ZONE_FAILURE = 'DELETE_ZONE_FAILURE';
export const DELETE_ZONE = 'DELETE_ZONE';
export const DELETE_ZONE_DATA = 'DELETE_ZONE_DATA';